apiVersion: v1
kind: Namespace
metadata:
  name: identity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: identity
spec:
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:latest
        args: ["--copy-service"]
        env:
        - name: LDAP_ORGANISATION
          value: "Vodafone Group Org"
        - name: LDAP_DOMAIN
          value: "vodafone.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "123mostafa1001"
        - name: LDAP_MODULES
          value: "memberof"
        - name: LDAP_BACKEND
          value: "mdb"
        ports:
        - containerPort: 389
          name: ldap
        volumeMounts:
        - name: seed-data
          mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom/users-groups.ldif
          subPath: users-groups.ldif
      volumes:
      - name: seed-data
        configMap:
          name: openldap-seed-data
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: identity
spec:
  selector:
    app: openldap
  ports:
  - port: 389
    targetPort: 389
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: identity
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args: ["start-dev"]
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "123mostafa1001"
        - name: KC_PROXY
          value: "edge"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME
          value: https://keycloak.34.54.147.73.sslip.io
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: identity
spec:
  selector:
    app: keycloak
  ports:
  - port: 80
    targetPort: 8080
